language: python
python:
    - "2.7"
    - "3.6"
# install dependancies
install:
    - cd API
    - source travis-env.sh
    - pip install -r requirements.txt
# run tests
script:
    - nosetests --with-coverage --cover-package app
# run coverage tests
after_success: 
    - coveralls
