language: python
python:
    - "2.7"
    - "3.6"
# install dependancies
install:
    - cd API
    - chmod +x travis-env.sh
    - ./travis-env.sh
    - pip install -r requirements.txt
# run tests
script:
    - nosetests test_endpoints.py
