language: python
python:
    - "2.7"
    - "3.6"

# install dependancies
install:
    - cd API
    - pip install pipenv
    - pipenv install
    - cp .envexample .env
# run tests
script:
    - pipenv shell --capture=no 
    - nosetests test_endpoints.py
